

video_links = {'Mysore Pak':['https://www.youtube.com/watch?v=XZOo2L2gKzo','https://www.youtube.com/watch?v=2E4GG6p48L0','https://www.youtube.com/watch?v=J_u5-SBxaz4','https://www.youtube.com/watch?v=s9p3jgC4Toc','https://www.youtube.com/watch?v=pLaHZoBPmVA'],
               'Ghevar': ['https://www.youtube.com/watch?v=zIKIw4lkSoM','https://www.youtube.com/watch?v=2B1w_Ndhcjk','https://www.youtube.com/watch?v=no0XCVRdv5Y','https://www.youtube.com/watch?v=8bw1uVGAatw','https://www.youtube.com/watch?v=tgdrU3YIddI'],
               'Sohan Papdi': ['https://www.youtube.com/watch?v=AOmVczqYIrg','https://www.youtube.com/watch?v=jTTrj40VJnI','https://www.youtube.com/watch?v=ky0nh_-Fl2g','https://www.youtube.com/watch?v=-fyfa1eOKFs','https://www.youtube.com/watch?v=2gkhKAvBwnw'],
               'Ras Malai': ['https://www.youtube.com/watch?v=znefLMNyVE8','https://www.youtube.com/watch?v=LECpZPkP9Wk','https://www.youtube.com/watch?v=9mm8my_NLlY','https://www.youtube.com/watch?v=DSocv7qa_3U','https://www.youtube.com/watch?v=qmooLr-IVe0'],
               'Ariselu': ['https://www.youtube.com/watch?v=i4QGIMdSzig','https://www.youtube.com/watch?v=PZRvGkAkHR4','https://www.youtube.com/watch?v=ApDgnNeYLmY','https://www.youtube.com/watch?v=LcA-9Wk9z_A','https://www.youtube.com/watch?v=mYxIotMspSM'],
               'Kofta': ['https://www.youtube.com/watch?v=oBR3nQUnhJc','https://www.youtube.com/watch?v=487VfUaTUdc','https://www.youtube.com/watch?v=soUKwdZS2zA','https://www.youtube.com/watch?v=Q4cSiiYa6_w','https://www.youtube.com/watch?v=c8Lh4vzSQG0'],
               'Aloo Tikki': ['https://www.youtube.com/watch?v=JOcnHa8FnBM','https://www.youtube.com/watch?v=BrYPnqA7eIg','https://www.youtube.com/watch?v=Er9CaLjTouA','https://www.youtube.com/watch?v=dYvJBSb2X7o','https://www.youtube.com/watch?v=zstT0kgIpP8'],
               'Gajar Ka Halwa': ['https://www.youtube.com/watch?v=0DDJ4mpSSfs','https://www.youtube.com/watch?v=CNJBC-TJJTA','https://www.youtube.com/watch?v=DLT7hC3oQFg','https://www.youtube.com/watch?v=LKzDV94y4p4','https://www.youtube.com/watch?v=-B1WBZqJQww'],
               'Chhena Kheeri': ['https://www.youtube.com/watch?v=jWPjm6gW_WU','https://www.youtube.com/watch?v=5iO5eQlF2nY','https://www.youtube.com/watch?v=xIhZXdTWOEk','https://www.youtube.com/watch?v=ba9zFDH3DMk','https://www.youtube.com/watch?v=v7ZpZbbTJeY'],
               'Kakinada Khaja': ['https://www.youtube.com/watch?v=kCnXvlhipko','https://www.youtube.com/watch?v=ZOq4QPkPKNI','https://www.youtube.com/watch?v=gJMWgrECz30','https://www.youtube.com/watch?v=hRVt8OYDNDY','https://www.youtube.com/watch?v=ZOq4QPkPKNI'],
               'Lassi': ['https://www.youtube.com/watch?v=g4As2DDoUVI','https://www.youtube.com/watch?v=E-eWorf6fmg','https://www.youtube.com/watch?v=c_IxCZrrHh8','https://www.youtube.com/watch?v=RCimLIOHcq4','https://www.youtube.com/watch?v=SlqpgRCdSyo'],
               'Naan': ['https://www.youtube.com/watch?v=WnkTTvAVisU','https://www.youtube.com/watch?v=zosoH5dH-uo','https://www.youtube.com/watch?v=3iQgO0XSo3c','https://www.youtube.com/watch?v=bkIrC7vGDQg','https://www.youtube.com/watch?v=RCimLIOHcq4'],
               'Chak Hao Kheer': ['https://www.youtube.com/watch?v=2bJLL7fJZAE','https://www.youtube.com/watch?v=_xKkkn4Di38','https://www.youtube.com/watch?v=9kBBEqAMvIM','https://www.youtube.com/watch?v=Gckq7RzmsZg','https://www.youtube.com/watch?v=h2-0ryTGczY'],
               'Butter Chicken': ['https://www.youtube.com/watch?v=NHKA-RVn5S4','https://www.youtube.com/watch?v=nF0uwlZiv84','https://www.youtube.com/watch?v=bX7AyuNMrVY','https://www.youtube.com/watch?v=a03U45jFxOI','https://www.youtube.com/watch?v=b7yuoRk227Y'],
               'Kajjikaya': ['https://www.youtube.com/watch?v=ckxI1zUc7VM','https://www.youtube.com/watch?v=XNS3J-HTwW4','https://www.youtube.com/watch?v=zXNJOkg4JY8','https://www.youtube.com/watch?v=VgrwTOfJdGM''https://www.youtube.com/watch?v=q3nUvM-9cIM'],
               'Chicken Razala': ['https://www.youtube.com/watch?v=pvGNv8spujA','https://www.youtube.com/watch?v=aa_IoKdmd78','https://www.youtube.com/watch?v=-axQN2u_354','https://www.youtube.com/watch?v=z8wDxmY6fxo','https://www.youtube.com/watch?v=6i6z-wZ7rW0'],
               'Lyangcha': ['https://www.youtube.com/watch?v=Tw-SzR6BqMQ','https://www.youtube.com/watch?v=a0D9zmwsNaY','https://www.youtube.com/watch?v=NHRGZjOxsQU','https://www.youtube.com/watch?v=zykTqH_F2iY','https://www.youtube.com/watch?v=zykTqH_F2iY'],
               'Aloo Gobi': ['https://www.youtube.com/watch?v=Iv-qfNzO6qQ','https://www.youtube.com/watch?v=0oZ6UxuFzis','https://www.youtube.com/watch?v=LPlSMI8bA6E','https://www.youtube.com/watch?v=Hnd8G-rCdaw','https://www.youtube.com/watch?v=s9jgq8wAxeM'],
               'Dal Makhani': ['https://www.youtube.com/watch?v=FTIjbV6yczo','https://www.youtube.com/watch?v=o3k55z-tv9I','https://www.youtube.com/watch?v=IrbbkVIPv2s','https://www.youtube.com/watch?v=dOiwccflDkY','https://www.youtube.com/watch?v=5RHl-JkKTvY'],
               'Bandar Laddu': ['https://www.youtube.com/watch?v=uIjFYIqkEAk','https://www.youtube.com/watch?v=ejJbDButM6g','https://www.youtube.com/watch?v=e_Vq1rbAuPE','https://www.youtube.com/watch?v=OQjfIMZdclA','https://www.youtube.com/watch?v=0ifYJrMePQA'],
               'Bhindi Masala': ['https://www.youtube.com/watch?v=ect1YiQALF8','https://www.youtube.com/watch?v=Vebrbb1y4f4','https://www.youtube.com/watch?v=phWpJjgocqU','https://www.youtube.com/watch?v=exvf8-cyCIw','https://www.youtube.com/watch?v=aXjcfzVujPI'],
               'Unni Appam': [],
               'Kuzhi Paniyaram': [],
               'Sandesh': [],
               'Sohan Halwa': [],
               'Rasgulla': [],
               'Shankarpali': [],
               'Pithe': [],
               'Imarti': [],
               'Misti Doi': [],
               'Navrattan Korma': [],
               'Daal Puri': [],
               'Malapua': [],
               'Dal Tadka': [],
               'Aloo Matar': [],
               'Palak Paneer': [],
               'Makki Di Roti Sarson Da Saag': [],
               'Poornalu': [],
               'Chicken Tikka': [],
               'Kadhi Pakoda': [],
               'Basundi': [],
               'Chapati': [],
               'Phirni': [],

               }
