catogries={
    'Mysore Pak':'Veg',
     'Ghevar':'Veg',
    'Sohan Papdi':'Veg',
    'Ras Malai':'Veg',
    'Ariselu':'Veg',
    'Kofta':'Veg',
    'Aloo Tikki':'Veg',
    'Gajar Ka Halwa':'Veg',
    'Chhena Kheeri':'Veg',
    'Kakinada Khaja':'Veg',
    'Lassi':'Veg',
    'Naan':'Veg',
    'Chak Hao Kheer':'Veg',
    'Butter Chicken':'Non-Veg',
    'Kajjikaya':'Veg',
    'Chicken Razala':'Non-Veg',
    'Lyangcha':'Veg',
    'Aloo Gobi':'Veg',
    'Dal Makhani':'Veg',
    'Bandar Laddu':'Veg',
    'Bhindi Masala':'Veg',
    'Unni Appam':'Veg',
    'Kuzhi Paniyaram':'Veg',
    'Sandesh':'Veg',
    'Sohan Halwa':'Veg',
    'Rasgulla':'Veg',
    'Shankarpali':'Veg',
    'Pithe':'Veg',
    'Imarti':'Veg',
    'Misti Doi':'Veg',
    'Navrattan Korma':'Veg',
    'Daal Puri':'Veg',
    'Malapua':'Veg',
    'Dal Tadka':'Veg',
    'Aloo Matar':'Veg',
    'Palak Paneer':'Veg',
    'Makki Di Roti Sarson Da Saag':'Veg',
    'Poornalu':'Veg',
    'Chicken Tikka':'Non-Veg',
    'Kadhi Pakoda':'Veg',
    'Basundi':'Veg',
    'Chapati':'Veg',
    'Phirni':'Veg',
    'Chikki':'Veg',
    'Sheera':'Veg',
    'Karela Bharta':'Veg',
    'Cham Cham':'Veg',
    'Shrikhand':'Veg',
    'Litti Chokha':'Veg',
    'Qubani Ka Meetha':'Veg',
    'Jalebi':'Veg',
    'Kachori':'Veg',
    'Aloo Methi':'Veg',
    'Maach Jhol':'Veg',
    'Kadai Paneer':'Veg',
    'Doodhpak':'Veg',
    'Chana Masala':'Veg',
    'Boondi':'Veg',
    'Misi Roti':'Veg',
    'Bhatura':'Veg',
    'Chicken Tikka Masala':'Non-Veg',
    'Double Ka Meetha':'Veg',
    'Kalakand':'Veg',
    'Poha':'Veg',
    'Adhirasam':'Veg',
    'Ledikeni':'Veg',
    'Dharwad Pedha':'Veg',
    'Dum Aloo':'Veg',
    'Sutar Feni':'Veg',
    'Gavvalu':'Veg',
    'Anarsa':'Veg',
    'Rabri':'Veg',
    'Daal Baati Churma':'Veg',
    'Sheer Korma':'Non-Veg',
    'Pootharekulu':'Veg',
    'Aloo Shimla Mirch':'Veg',
    'Gulab Jamun':'Veg',
    'Paneer Butter Masala':'Veg',
    'Modak':'Veg',
    'Biryani':'Veg',
}