catogries={
    'Mysore Pak':'Veg',
     'Ghevar':'Veg',
    'Sohan Papdi':'Veg',
    'Ras Malai':'Veg',
    'Ariselu':312,
    'Kofta':'Veg',
    'Aloo Tikki':'Veg',
    'Gajar Ka Halwa':'Veg',
    'Chhena Kheeri':'Veg',
    'Kakinada Khaja':'Veg',
    'Lassi':'Veg',
    'Naan':'Veg',
    'Chak Hao Kheer':'Veg',
    'Butter Chicken':'Non-Veg',
    'Kajjikaya':'Veg',
    'Chicken Razala':'Non-Veg',
    'Lyangcha':250,
    'Aloo Gobi':'Veg',
    'Dal Makhani':'Veg',
    'Bandar Laddu':'Veg',
    'Bhindi Masala':'Veg',
    'Unni Appam':'Veg',
    'Kuzhi Paniyaram':18,
    'Sandesh':188,
    'Sohan Halwa':'Veg',
    'Rasgulla':'Veg',
    'Shankarpali':33,
    'Pithe':120,
    'Imarti':'Veg',
    'Misti Doi':'Veg',
    'Navrattan Korma':223,
    'Daal Puri':'Veg',
    'Malapua':'Veg',
    'Dal Tadka':'Veg',
    'Aloo Matar':'Veg',
    'Palak Paneer':'Veg',
    'Makki Di Roti Sarson Da Saag':'Veg',
    'Poornalu':'Veg',
    'Chicken Tikka':'Non-Veg',
    'Kadhi Pakoda':'Veg',
    'Basundi':'Veg',
    'Chapati':'Veg',
    'Phirni':344,
    'Chikki':'Veg',
    'Sheera':'Veg',
    'Karela Bharta':'Veg',
    'Cham Cham':'Veg',
    'Shrikhand':'Veg',
    'Litti Chokha':'Veg',
    'Qubani Ka Meetha':390,
    'Jalebi':'Veg',
    'Kachori':'Veg',
    'Aloo Methi':'Veg',
    'Maach Jhol':'Veg',
    'Kadai Paneer':'Veg',
    'Doodhpak':'Veg',
    'Chana Masala':'Veg',
    'Boondi':'Veg',
    'Misi Roti':'Veg',
    'Bhatura':'Veg',
    'Chicken Tikka Masala':'Veg',
    'Double Ka Meetha':407,
    'Kalakand':142,
    'Poha':'Veg',
    'Adhirasam':312,
    'Ledikeni':125,
    'Dharwad Pedha':'Veg',
    'Dum Aloo':'Veg',
    'Sutar Feni':'Veg',
    'Gavvalu':240,
    'Anarsa':304,
    'Rabri':'Veg',
    'Daal Baati Churma':'Veg',
    'Sheer Korma':'Non-Veg',
    'Pootharekulu':158,
    'Aloo Shimla Mirch':'Veg',
    'Gulab Jamun':'Veg',
    'Paneer Butter Masala':'Veg',
    'Modak':'Veg',
    'Biryani':'Veg',
}